### ISSUE TITLE
AnnealMaker --> ZeroDivisionError

### ISSUE THREAD

**Issue by xperrylinn** [xperrylinn/atomate2-openmm#15]
For the parameters reference [here](https://github.com/xperrylinn/atomate2-openmm/pull/14/commits/4df7edad7ec3db29fcbe0c41e388eb5d796723dd), I'm getting a `ZeroDivisionError` in the AnnelMaker.
```
Traceback (most recent call last):
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/jobflow/managers/local.py", line 98, in _run_job
    response = job.run(store=store)
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/jobflow/core/job.py", line 544, in run
    response = function(*self.function_args, **self.function_kwargs)
  File "/Users/xperrylinn/Documents/Academics/MSSE/spring_2023/Capstone/atomate2-openmm/src/atomate2/openmm/jobs/base_openmm_maker.py", line 101, in make
    task_details = self._run_openmm(sim)
  File "/Users/xperrylinn/Documents/Academics/MSSE/spring_2023/Capstone/atomate2-openmm/src/atomate2/openmm/jobs/temp_change_maker.py", line 24, in _run_openmm
    for temp in np.arange(
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/openmm/unit/quantity.py", line 408, in __truediv__
    return (self/other._value) / other.unit
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/openmm/unit/quantity.py", line 411, in __truediv__
    return self * pow(other, -1.0)
ZeroDivisionError: 0.0 cannot be raised to a negative power
```

**Comment by xperrylinn** [comment]
Handled by https://github.com/xperrylinn/atomate2-openmm/pull/16.
